// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyApi.Services.SQLServer;

namespace PolicyApi.Migrations
{
    [DbContext(typeof(PolicyStore))]
    [Migration("20200816162000_PolicyStore.v1")]
    partial class PolicyStorev1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolicyApi.DataModels.PermissionCategories", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISPLAY_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POSITION")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PERMISSION_CATEGORIES");
                });

            modelBuilder.Entity("PolicyApi.DataModels.Permissions", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISPLAY_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERMISSION_CATEDGORY_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("POSITION")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PERMISSION_CATEDGORY_ID");

                    b.ToTable("PERMISSIONS");
                });

            modelBuilder.Entity("PolicyApi.DataModels.ProfileRolePermissions", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PERMISSION_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PROFILE_ROLE_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("PERMISSION_ID");

                    b.HasIndex("PROFILE_ROLE_ID");

                    b.ToTable("PROFILE_ROLE_PERMISSIONS");
                });

            modelBuilder.Entity("PolicyApi.DataModels.ProfileRoles", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PROFILE_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROLE_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ROLE_ID");

                    b.ToTable("PROFILE_ROLES");
                });

            modelBuilder.Entity("PolicyApi.DataModels.Roles", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("POSITION")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("PolicyApi.DataModels.Permissions", b =>
                {
                    b.HasOne("PolicyApi.DataModels.PermissionCategories", "PERMISSION_CATEGORIES")
                        .WithMany()
                        .HasForeignKey("PERMISSION_CATEDGORY_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolicyApi.DataModels.ProfileRolePermissions", b =>
                {
                    b.HasOne("PolicyApi.DataModels.Permissions", "PERMISSIONS")
                        .WithMany()
                        .HasForeignKey("PERMISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolicyApi.DataModels.ProfileRoles", "PROFILE_ROLES")
                        .WithMany()
                        .HasForeignKey("PROFILE_ROLE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolicyApi.DataModels.ProfileRoles", b =>
                {
                    b.HasOne("PolicyApi.DataModels.Roles", "ROLES")
                        .WithMany()
                        .HasForeignKey("ROLE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
