name: PolicyApi

trigger:
- main

# resources:
#   repositories:
#     - repository: templates
#       type: github
#       name: itsbibeksaini/pipeline-templates
#       endpoint: github.com_itsbibeksaini

pr: none

pool:
  vmImage: ubuntu-latest

# variables:  
#   imageRepository: 'policyapi'
#   helmChart: './policyapi-chart'  
#   valueFile: './policyapi-chart/values.yaml'
#   tag: $(Build.SourceBranchName)_$(Build.SourceVersion)
#   vmImageName: ubuntu-latest

stages:
- stage: BuildImage
  displayName: Build and push .NET Application
  jobs:  
  - job: Build
    steps:         
      - task: UseDotNet@2
        inputs:
          version: '6.0.x'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          feedsToUse: 'select'
          projects: "**/*.csproj"
          includeNuGetOrg: true
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: ./PolicyApi.sln
    
# - stage: Deploy
#   displayName: Helm Deploy
#   jobs:
#     - job: Deploy
#       pool:
#        vmImage: $(vmImageName)
#       steps:         
#       - template: helm-deploy.yml@templates
#         parameters:
#           helmChart: $(helmChart)
#           imageRepository: $(imageRepository)
#           valueFile: $(valueFile)
#           tag: $(tag)