apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "policyapi-chart.fullname" . }}
  labels:
    {{- include "policyapi-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "policyapi-chart.selectorLabels" . | nindent 6 }}
      app: {{ include "policyapi-chart.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "policyapi-chart.selectorLabels" . | nindent 8 }}
        app: {{ include "policyapi-chart.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "policyapi-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "ASPNETCORE_URLS"
              value: "http://[*]:8080"
            - name: "JwtSecretKey__PRIVATE_KEY"
              valueFrom:
                secretKeyRef:
                  name: tmsolution-jwt-secrets
                  key: PRIVATE_KEY
                  optional: false
            - name: "JwtSecretKey__PUBLIC_KEY"
              valueFrom:
                secretKeyRef:
                  name: tmsolution-jwt-secrets
                  key: PUBLIC_KEY
                  optional: false
            - name: "JwtSecretKey__ISSUER"
              valueFrom:
                secretKeyRef:
                  name: tmsolution-jwt-secrets
                  key: ISSUER
                  optional: false
            - name: "JwtSecretKey__AUDIENCE"
              valueFrom:
                secretKeyRef:
                  name: tmsolution-jwt-secrets
                  key: AUDIENCE
                  optional: false
            - name: "JwtSecretKey__TTL"
              valueFrom:
                secretKeyRef:
                  name: tmsolution-jwt-secrets
                  key: TTL
                  optional: false
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 6900
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
