apiVersion: v1
kind: Service
metadata:
  name: {{ include "policyapi-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $key, $value := .Values.service.Ports }}
  - name: {{ $key }}
{{ toYaml $value | indent 4 }}
{{- end }}
  selector:
    app: {{ include "policyapi-chart.fullname" . }}
