apiVersion : apps/v1
kind: Deployment
metadata:
  name: policyapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policyapi
  template:
    metadata:
      labels:
        app: policyapi
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-name": "policyapi"
        "consul.hashicorp.com/connect-service-port": "5003"
    spec:
      containers:
        - name: policyapi
          image: policyapi:v1
          env:
            - name: "ASPNETCORE_URLS"
              value: "https://[*]:5003"
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Password"
              value: "Bibek123@"
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
              value: "secret/tmsolution.pfx"
          ports:
          - containerPort: 5003
          volumeMounts:
          - mountPath: /app/secret
            name: tmsolution-secret
      volumes:
        - name: tmsolution-secret
          secret:
            secretName: tmsolution-generic-secret
