name: Poilcy API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:
    uses: itsbibeksaini/github-workflows/.github/workflows/dotnet-build-and-push.yml@main
    with:
      SOLUTION_FILE: ./PolicyApi.sln
      PROJECT_FILE: ./PolicyApi/PolicyApi.csproj
      TEST_PROJECT_FILE: ./PolicyApiTest/PolicyApiTest.csproj
      IMAGE_NAME: policyapi
