name: Poilcy API

on:
  push:
    branches: new-workflow
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:
    uses: itsbibeksaini/github-workflows/.github/workflows/dotnet-build-and-push.yml@main
    with:
      SOLUTION_FILE: ./PolicyApi.sln
      PROJECT_FILE: ./PolicyApi/PolicyApi.csproj
      TEST_PROJECT_FILE: ./PolicyApiTest/PolicyApiTest.csproj
      IMAGE_NAME: policyapi
      DOCKER_FILE: PolicyApi/Dockerfile
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}

  deploy:
    uses: itsbibeksaini/github-workflows/.github/workflows/helm-deploy.yml@main
    needs: build
    with:
      IMAGE_NAME: policyapi
      HELM_CHARTS: ./policyapi-chart 
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
