name: Poilcy API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:
    uses: itsbibeksaini/github-workflows/.github/workflows/dotnet-build.yml@main
    with:
      SOLUTION_FILE: ./PolicyApi.sln
      PROJECT_FILE: ./PolicyApi/PolicyApi.csproj
      TEST_PROJECT_FILE: ./PolicyApiTest/PolicyApiTest.csproj
      PROJECT_NAME: PolicyApi
  
  image:
    uses: itsbibeksaini/github-workflows/.github/workflows/docker-build.yml@main
    needs: build
    with:
      DOCKERFILE: "PolicyApi/Dockerfile"
      IMAGE_NAME: "policyapi"
      PROJECT_NAME: PolicyApi
  
  push:
    uses: itsbibeksaini/github-workflows/.github/workflows/docker-push-image.yml@main
    needs: image
    with:
      IMAGE_NAME: "policyapi"
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
  deploy:
    uses: itsbibeksaini/github-workflows/.github/workflows/helm-deploy.yml@main
    needs: push
    with:
      IMAGE_NAME: "policyapi"
      HELM_CHARTS: "./policyapi-chart"
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
